# .github/workflows/sync-upstream.yml
name: Sync Upstream

on:
  schedule:
    - cron: "0 2 * * *"  # 每天凌晨2点同步
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 需要完整的 commit 历史

      # - name: Set up Git user
      #   run: |
      #     git config --global user.name "GitHub Actions"
      #     git config --global user.email "github-actions@github.com"

      # - name: Add upstream and fetch
      #   run: |
      #     git remote add upstream https://github.com/78/xiaozhi-esp32.git
      #     git fetch upstream
  
      - name: Merge upstream changes
        run: |
          git fetch upstream
          git checkout main
          git merge upstream/main --allow-unrelated-histories
          git push origin main  # 关键：推送回仓库